language: cpp
branches:
  only:
    - master
matrix:
  include:

    # ubuntu trusty gcc 4.8 (default for trusty)
    - os: linux
      dist: trusty
      compiler: gcc

    # ubuntu trusty gcc 4.9
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # ubuntu trusty gcc 5
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # ubuntu trusty gcc 6
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # ubuntu trusty gcc 7
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # ubuntu trusty clang 3.6
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    # ubuntu trusty clang 3.7
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

    # ubuntu trusty clang 3.8
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    # ubuntu trusty clang 3.9
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    # ubuntu trusty clang 4.0
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # ubuntu trusty clang 5.0
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    # macOS 10.10
    - os: osx
      osx_image: xcode6.4

    # macOS 10.11
    - os: osx
      osx_image: xcode7.3

    # macOS 10.11
    - os: osx
      osx_image: xcode8

    # macOS 10.12
    - os: osx
      osx_image: xcode8.3

    # macOS 10.12
    - os: osx
      osx_image: xcode9.0

    # macOS 10.12
    - os: osx
      osx_image: xcode9.1

    # macOS 10.12
    - os: osx
      osx_image: xcode9.2

    # macOS 10.13
    - os: osx
      osx_image: xcode9.3beta

before_install:
 - eval "${MATRIX_EVAL}"
# - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                 ; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install boost                          ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:kzemek/boost -y           ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                   ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install boost1.58                        ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-filesystem1.58-dev      ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-chrono1.58-dev          ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-date-time1.58-dev       ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-serialization1.58-dev   ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-regex1.58-dev           ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-program-options1.58-dev ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-system1.58-dev          ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-thread1.58-dev          ; fi

script:
  - make -j2 release
